### ISSUE TITLE
Connect to GitHub and create a release

### ISSUE THREAD

**Issue by llorllale** [llorllale/releasecat-maven-plugin#1]
Obtain user credentials and create a release

**Comment by 0pdd** [comment]
@llorllale the puzzle [#3](https://github.com/llorllale/releasecat-maven-plugin/issues/3) is still not solved.

**Comment by 0pdd** [comment]
@llorllale the puzzle [#4](https://github.com/llorllale/releasecat-maven-plugin/issues/4) is still not solved.

**Comment by 0pdd** [comment]
@llorllale the puzzle [#5](https://github.com/llorllale/releasecat-maven-plugin/issues/5) is still not solved.

**Comment by 0pdd** [comment]
@llorllale the puzzle [#7](https://github.com/llorllale/releasecat-maven-plugin/issues/7) is still not solved.

**Comment by 0pdd** [comment]
@llorllale the puzzle [#8](https://github.com/llorllale/releasecat-maven-plugin/issues/8) is still not solved.

**Comment by 0pdd** [comment]
@llorllale the puzzle [#10](https://github.com/llorllale/releasecat-maven-plugin/issues/10) is still not solved.

**Comment by 0pdd** [comment]
@llorllale the last puzzle [#8](https://github.com/llorllale/releasecat-maven-plugin/issues/8) is solved here.

**Comment by 0pdd** [comment]
@llorllale 4 puzzles [#10](https://github.com/llorllale/releasecat-maven-plugin/issues/10), [#13](https://github.com/llorllale/releasecat-maven-plugin/issues/13), [#14](https://github.com/llorllale/releasecat-maven-plugin/issues/14), [#7](https://github.com/llorllale/releasecat-maven-plugin/issues/7) are still not solved; solved: [#3](https://github.com/llorllale/releasecat-maven-plugin/issues/3), [#4](https://github.com/llorllale/releasecat-maven-plugin/issues/4), [#5](https://github.com/llorllale/releasecat-maven-plugin/issues/5), [#8](https://github.com/llorllale/releasecat-maven-plugin/issues/8).

**Comment by 0pdd** [comment]
@llorllale 5 puzzles [#10](https://github.com/llorllale/releasecat-maven-plugin/issues/10), [#13](https://github.com/llorllale/releasecat-maven-plugin/issues/13), [#16](https://github.com/llorllale/releasecat-maven-plugin/issues/16), [#17](https://github.com/llorllale/releasecat-maven-plugin/issues/17), [#7](https://github.com/llorllale/releasecat-maven-plugin/issues/7) are still not solved; solved: [#14](https://github.com/llorllale/releasecat-maven-plugin/issues/14), [#3](https://github.com/llorllale/releasecat-maven-plugin/issues/3), [#4](https://github.com/llorllale/releasecat-maven-plugin/issues/4), [#5](https://github.com/llorllale/releasecat-maven-plugin/issues/5), [#8](https://github.com/llorllale/releasecat-maven-plugin/issues/8).

**Comment by 0pdd** [comment]
@llorllale 5 puzzles [#10](https://github.com/llorllale/releasecat-maven-plugin/issues/10), [#13](https://github.com/llorllale/releasecat-maven-plugin/issues/13), [#16](https://github.com/llorllale/releasecat-maven-plugin/issues/16), [#19](https://github.com/llorllale/releasecat-maven-plugin/issues/19), [#7](https://github.com/llorllale/releasecat-maven-plugin/issues/7) are still not solved; solved: [#14](https://github.com/llorllale/releasecat-maven-plugin/issues/14), [#17](https://github.com/llorllale/releasecat-maven-plugin/issues/17), [#3](https://github.com/llorllale/releasecat-maven-plugin/issues/3), [#4](https://github.com/llorllale/releasecat-maven-plugin/issues/4), [#5](https://github.com/llorllale/releasecat-maven-plugin/issues/5), [#8](https://github.com/llorllale/releasecat-maven-plugin/issues/8).

**Comment by 0pdd** [comment]
@llorllale 4 puzzles [#10](https://github.com/llorllale/releasecat-maven-plugin/issues/10), [#13](https://github.com/llorllale/releasecat-maven-plugin/issues/13), [#16](https://github.com/llorllale/releasecat-maven-plugin/issues/16), [#7](https://github.com/llorllale/releasecat-maven-plugin/issues/7) are still not solved; solved: [#14](https://github.com/llorllale/releasecat-maven-plugin/issues/14), [#17](https://github.com/llorllale/releasecat-maven-plugin/issues/17), [#19](https://github.com/llorllale/releasecat-maven-plugin/issues/19), [#3](https://github.com/llorllale/releasecat-maven-plugin/issues/3), [#4](https://github.com/llorllale/releasecat-maven-plugin/issues/4), [#5](https://github.com/llorllale/releasecat-maven-plugin/issues/5), [#8](https://github.com/llorllale/releasecat-maven-plugin/issues/8).

**Comment by 0pdd** [comment]
@llorllale 3 puzzles [#10](https://github.com/llorllale/releasecat-maven-plugin/issues/10), [#16](https://github.com/llorllale/releasecat-maven-plugin/issues/16), [#7](https://github.com/llorllale/releasecat-maven-plugin/issues/7) are still not solved; solved: [#13](https://github.com/llorllale/releasecat-maven-plugin/issues/13), [#14](https://github.com/llorllale/releasecat-maven-plugin/issues/14), [#17](https://github.com/llorllale/releasecat-maven-plugin/issues/17), [#19](https://github.com/llorllale/releasecat-maven-plugin/issues/19), [#3](https://github.com/llorllale/releasecat-maven-plugin/issues/3), [#4](https://github.com/llorllale/releasecat-maven-plugin/issues/4), [#5](https://github.com/llorllale/releasecat-maven-plugin/issues/5), [#8](https://github.com/llorllale/releasecat-maven-plugin/issues/8).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#10](https://github.com/llorllale/releasecat-maven-plugin/issues/10), [#16](https://github.com/llorllale/releasecat-maven-plugin/issues/16) are still not solved; solved: [#13](https://github.com/llorllale/releasecat-maven-plugin/issues/13), [#14](https://github.com/llorllale/releasecat-maven-plugin/issues/14), [#17](https://github.com/llorllale/releasecat-maven-plugin/issues/17), [#19](https://github.com/llorllale/releasecat-maven-plugin/issues/19), [#3](https://github.com/llorllale/releasecat-maven-plugin/issues/3), [#4](https://github.com/llorllale/releasecat-maven-plugin/issues/4), [#5](https://github.com/llorllale/releasecat-maven-plugin/issues/5), [#7](https://github.com/llorllale/releasecat-maven-plugin/issues/7), [#8](https://github.com/llorllale/releasecat-maven-plugin/issues/8).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#16](https://github.com/llorllale/releasecat-maven-plugin/issues/16) is still not solved; solved: [#10](https://github.com/llorllale/releasecat-maven-plugin/issues/10), [#13](https://github.com/llorllale/releasecat-maven-plugin/issues/13), [#14](https://github.com/llorllale/releasecat-maven-plugin/issues/14), [#17](https://github.com/llorllale/releasecat-maven-plugin/issues/17), [#19](https://github.com/llorllale/releasecat-maven-plugin/issues/19), [#3](https://github.com/llorllale/releasecat-maven-plugin/issues/3), [#4](https://github.com/llorllale/releasecat-maven-plugin/issues/4), [#5](https://github.com/llorllale/releasecat-maven-plugin/issues/5), [#7](https://github.com/llorllale/releasecat-maven-plugin/issues/7), [#8](https://github.com/llorllale/releasecat-maven-plugin/issues/8).

**Comment by 0pdd** [comment]
@llorllale all 11 puzzles are solved here: [#10](https://github.com/llorllale/releasecat-maven-plugin/issues/10), [#13](https://github.com/llorllale/releasecat-maven-plugin/issues/13), [#14](https://github.com/llorllale/releasecat-maven-plugin/issues/14), [#16](https://github.com/llorllale/releasecat-maven-plugin/issues/16), [#17](https://github.com/llorllale/releasecat-maven-plugin/issues/17), [#19](https://github.com/llorllale/releasecat-maven-plugin/issues/19), [#3](https://github.com/llorllale/releasecat-maven-plugin/issues/3), [#4](https://github.com/llorllale/releasecat-maven-plugin/issues/4), [#5](https://github.com/llorllale/releasecat-maven-plugin/issues/5), [#7](https://github.com/llorllale/releasecat-maven-plugin/issues/7), [#8](https://github.com/llorllale/releasecat-maven-plugin/issues/8).
